name: 📚 Documentation including README.md
description: File a bug/issue for docs or README.md
title: "[bug] <title>"
labels: [docs, needs-triage]
assignees:
  - bhdicaire
body:
- type: textarea
  attributes:
    label: Docs/README.md Part to update
    description: A concise description of what you thing should be updated
  validations:
    required: true
